# Generated by Django 2.1.2 on 2020-02-22 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearnerapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
