# Generated by Django 2.1.2 on 2020-02-27 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearnerapp', '0005_auto_20200227_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='question',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='ques',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elearnerapp.Question'),
        ),
    ]
