# Generated by Django 2.1.2 on 2020-03-02 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearnerapp', '0007_auto_20200227_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(default='E', max_length=5)),
                ('ques', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elearnerapp.Question')),
            ],
        ),
    ]
