# Generated by Django 2.1.2 on 2020-03-02 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearnerapp', '0008_useranswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='ques',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearnerapp.Question'),
        ),
    ]
