# Generated by Django 2.1.2 on 2020-03-02 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearnerapp', '0013_auto_20200302_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='questionnaire',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='ques',
        ),
    ]
